# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

title: Quelli del non-senso
description: Happy blogging... ❤
github_username: 

# Email and twitter are optional:
email:
twitter_username:

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics:

# Note: render only in production environment
enableComments = true

# directly load the comments after pages loaded
autoLoadComments = true

--*- Snip -*--

## Utterances
enableUtterances = true
utterancesRepo = "istrik/istrik.github.io" # Change the repository to match your GitHub username and repo
utterancesIssueTerm = "pathname"
utterancesTheme = "github-light"
utterancesThemeDark = "photon-dark"
utterancesLabel = ""
# Note: https://utteranc.es/

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

titles_from_headings:
  enabled:     false
  strip_title: false
  collections: false

highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
